[package]
name = "impellers"
version = "0.4.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/coderedart/flutter"
readme = "README.md"
description = "Bindings to Flutter's 2D vector graphics renderer"
links = "impeller"
exclude = ["/flutter"] # flutter sources are too large and we don't support source builds anyway.

[features]
default = []
sys = []

# Generates bindings to impeller header as part of build.rs.
# Without this feature, we will use pre-generated bindings for all 64-bit targets.
bindgen_live = ["dep:bindgen", "dep:anyhow", "dep:tracing", "dep:tracing-subscriber", "dep:serde_json"]

# This downloads and links the prebuilt-libs of impeller using curl and tar.
prebuilt_libs = []
static_link = ["prebuilt_libs"] # enables static linking (only on linux/windows/mac)
# will create a .impeller_cache beside target directory and stores the downloaded libraries
# Will skip redownloading libs if they can be found in .impeller_cache. please add the directory to .gitignore
cache_libs = ["prebuilt_libs"]

internal_pre_bindgen = ["bindgen_live"]


[dependencies]
euclid = {version = "0.22", features = ["bytemuck"]}
bytemuck = {version = "1"}
bitflags = {version = "2"}

[build-dependencies]
bindgen = {version = "0.72", optional = true}
anyhow = {version = "1", optional = true}
tracing = {version = "0.1", optional = true}
tracing-subscriber = {version = "0.3", features = ["fmt", "env-filter"], optional = true}
serde_json = {version = "1", optional = true}

[dev-dependencies]
glfw = {version = "0.62", features = ["vulkan"]}
ash = {version = "0.38"}
glow = {version = "0.18"}
image = {version  = "0.25", default-features = false, features = ["jpeg"]}

[[example]]
name = "empty"
required-features = ["sys", "prebuilt_libs"]

[[example]]
name = "common"
crate-type = ["staticlib"]
doc-scrape-examples = true




[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]