on:
    push:
      branches:
        - master
name: Check Rust Crate
# This just runs the rust crate example to verify that it builds (no undefined references error)
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Glfw on Ubuntu
      if: matrix.os == 'ubuntu'
      # based on glfw/glfw's workflow
      run: sudo apt install -y libglfw3-dev libglfw3 libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
    - name: Shared Build
      shell: bash
      run: |
        cargo run --example=empty --features=prebuilt_libs,sys

    - name: Static Build
      shell: bash
      if: matrix.os != 'macos'
      run: |
        cargo run --example=empty --features=prebuilt_libs,sys,static_link
